### ISSUE TITLE
Slightly better docs

### ISSUE THREAD

**Issue by johngruen** [ozten/commit#3]
Hey @ozten i'm not a ruby dev, but I'd love to build you guys a better stylesheet. Could i get a few quickstart docs? Having trouble standing up a server locally.

**Comment by ozten** [comment]
Sorry about that. Let me get on that tomorrow morning!

**Comment by ozten** [comment]
Okay, Check out [DEV.md](https://github.com/ozten/commit/blob/master/DEV.md). I've tested the steps, but let me know if you have any issues or questions.
